version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_catalog
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/movie_catalog
    ports:
      - '8000:8000'

volumes:
  postgres_data:
